### PR TITLE
add postgresql `contrib` package

### PR DESCRIPTION
**Pull request by TakoB222**

### CODE REVIEW

**Review by dragomirp — APPROVED** [review]
LGTM

**Review by marceloneppel — APPROVED** [review]
LGTM!

**Comment by dragomirp** [comment]
Hi, @TakoB222, please sign the [CLA](https://github.com/juju/juju/blob/3.3/CONTRIBUTING.md#contributor-licence-agreement), so that we can merge. Thanks.

**Comment by TakoB222** [comment]
> Hi, @TakoB222, please sign the [CLA](https://github.com/juju/juju/blob/3.3/CONTRIBUTING.md#contributor-licence-agreement), so that we can merge. Thanks.

Done!

**Review by taurus-forever — APPROVED** [review]

**Pull request merged**
