### PR TITLE
[DPE-2765] added new packages

### PR DESCRIPTION
**Pull request by TakoB222**
## Issue
Add snap packages to support such postgresql extensions:
 - icu_ext
 - address_standardizer
 - address_standardizer_data_us
 - bool_plperl
 - hll
 - hstore
 - hypopg
 - ip4r
 - jsonb_plperl
 - orafce
 - pg_similarity
 - pg_trgm
 - plperl
 - pltcl
 - postgis_raster
 - postgis_tiger_geocoder
 - postgis_topology
 - prefix
 - rdkit
 - tds_fdw
 - unaccent
 - PostGIS
> ## Solution
Added postgresql packages which contains extensions from the list above:
 - postgresql-plperl-14
 - postgresql-14-similarity
 - postgresql-14-orafce
 - postgresql-14-hypopg
 - postgresql-14-hll
 - postgresql-14-ip4r
 - postgresql-pltcl-14
 - postgresql-14-prefix
 - postgresql-14-rdkit
 - postgresql-14-tds-fdw
 - postgresql-14-icu-ext
 - postgresql-14-postgis-3
 - postgresql-14-postgis-3-scripts

##
Building time:
  snapcraft clean && time snapcraft pack
  real	1m50.780s  # before the PR
  real	3m16.293s  # after the PR
  
Snap size:
  -rw-r--r-- 1 ubuntu ubuntu 116101120 Nov 27 17:57 charmed-postgresql_14.9_amd64.snap # before this PR merge
  -rw-r--r-- 1 ubuntu ubuntu 180645888 Nov 27 18:02 charmed-postgresql_14.9_amd64.snap # after this PR merge

### CODE REVIEW

**Review by marceloneppel — APPROVED** [review]

**Review by delgod — APPROVED** [review]

**Comment by marceloneppel** [comment]
@TakoB222, is it possible to break lines in the snap? Lines 60, 62, 66 and 93. The lint job is complaining about them. If it's not possible, or the solution doesn't looks good, we can see what can be done to make that job accept longer lines.

**Comment by TakoB222** [comment]
> @TakoB222, is it possible to break lines in the snap? Lines 60, 62, 66 and 93. The lint job is complaining about them. If it's not possible, or the solution doesn't looks good, we can see what can be done to make that job accept longer lines.

Should be fixed

**Review by dragomirp — APPROVED** [review]

**Review by taurus-forever — CHANGES_REQUESTED** [review]
Thank you @TakoB222 ! LGTM, but please:
1) always add a useful description to PR (to provide nice commit message after merging) and ticket reference. You can use [DPE-2765](https://warthogs.atlassian.net/browse/DPE-2765) here.
2) please check the `License` folder and mention at lest PostGIS there.
3) It is great to report in PR message the expected changes, e.g. building time and the result size:
```
-rw-r--r-- 1 ubuntu ubuntu  98320384 Apr 18  2023 charmed-postgresql_14.7_amd64.snap # 14.7 in 23.04 time
-rw-r--r-- 1 ubuntu ubuntu 116101120 Nov 27 17:57 charmed-postgresql_14.9_amd64.snap # before this PR merge
-rw-r--r-- 1 ubuntu ubuntu 180645888 Nov 27 18:02 charmed-postgresql_14.9_amd64.snap # after this PR merge 


Building time:
> snapcraft clean && time snapcraft pack
real	1m50.780s  # before the PR
real	3m16.293s  # after the PR
```
2 @delgod :
1) ~PostGIS only doubled the SNAP size.
2) surprisingly found in [backlog](https://warthogs.atlassian.net/browse/DPE-1573) (re-assigned to Shayan for the next pulse to apply [MySQL PR](https://github.com/canonical/charmed-mysql-snap/pull/36) on PostgreSQL as well).

**Comment by TakoB222** [comment]
> Thank you @TakoB222 ! LGTM, but please:
> 
> 1. always add a useful description to PR (to provide nice commit message after merging) and ticket reference. You can use [DPE-2765](https://warthogs.atlassian.net/browse/DPE-2765) here.
> 2. please check the `License` folder and mention at lest PostGIS there.
> 3. It is great to report in PR message the expected changes, e.g. building time and the result size:
> 
> ```
> -rw-r--r-- 1 ubuntu ubuntu  98320384 Apr 18  2023 charmed-postgresql_14.7_amd64.snap # 14.7 in 23.04 time
> -rw-r--r-- 1 ubuntu ubuntu 116101120 Nov 27 17:57 charmed-postgresql_14.9_amd64.snap # before this PR merge
> -rw-r--r-- 1 ubuntu ubuntu 180645888 Nov 27 18:02 charmed-postgresql_14.9_amd64.snap # after this PR merge 
> 
> 
> Building time:
> > snapcraft clean && time snapcraft pack
> real	1m50.780s  # before the PR
> real	3m16.293s  # after the PR
> ```
> 
> 2 @delgod :
> 
> 1. ~PostGIS only doubled the SNAP size.
> 2. surprisingly found in [backlog](https://warthogs.atlassian.net/browse/DPE-1573) (re-assigned to Shayan for the next pulse to apply [MySQL PR](https://github.com/canonical/charmed-mysql-snap/pull/36) on PostgreSQL as well).

Okay, thanks, noted

[DPE-2765]: https://warthogs.atlassian.net/browse/DPE-2765?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Review by taurus-forever — APPROVED** [review]
LGTM! 

P.S. @7annaba3l is re-checking licensing before merging it.

Thank you!

**Pull request merged**
